# Generated by Django 3.2.23 on 2023-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTarea', models.CharField(max_length=250)),
                ('descrip', models.CharField(max_length=250)),
                ('hecha', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
